services:
  - type: web
    name: omixbooks
    runtime: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
